# Generated by Django 6.0.2 on 2026-02-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
