# Generated by Django 6.0.2 on 2026-03-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0006_alter_data_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
