# Generated by Django 6.0.2 on 2026-03-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0008_alter_data_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
